name: CI

on: [push, pull_request]

jobs:
  test-plugin:
    name: Linux x64_64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        echo "REPODIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "APPDIR=/tmp/AppDir"        >> $GITHUB_ENV

    - name: Setup dependencies
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install -y -qq libncurses-dev wget tree

    - name: Download external binairies
      run: |
        wget -qc "https://raw.githubusercontent.com/linuxdeploy/misc-plugins/master/tests/test-plugins.sh"
        chmod +x *.sh

    - name: Run test script
      run: |
        mkdir -pv "$APPDIR"
        ./test-plugins.sh

    - name: Display files inside AppDir
      run: tree "$APPDIR"
